version: '2'

services:
  hubot:
    build: .
    ports:
      - 8080:8080
    environment:
      - HUBOT_SLACK_TOKEN=<slack token | ex) xoxb-....>
      - HUBOT_SLACK_TEAM=<slack team | ex) hogehoge.slack.team>
      - HUBOT_SLACK_BOTNAME=miyuki